### ISSUE TITLE
Styling + Responsive UI

### ISSUE THREAD

**Issue by xyntechx** [hashrock/my-clock#2]
Hi! I saw the website and it has an interesting concept! I'd like to contribute, particularly in the design (maybe add some colours, adjust the bar graphs' length, etc.) and making the website mobile responsive. Happy to submit a PR if that's alright with you!

**Comment by hashrock** [comment]
Thank you! Of course I welcome your contributions!
I was originally going to display this on my old iPhone and use it in place of a clock, but gave up because my browser version was probably too old to run it.
So you may change the layout and design as you like. Perhaps we could make it a PWA or Native App using electron or something.

**Comment by xyntechx** [comment]
PR made!
